Repository simonefuoco/tappy, pull requests merged in 2019-10, with the labels that each got.

#5 Add license & updated readme
  .gitignore
  LICENSE
  README.md
  license.txt
  readme.html
Labels: documentation

#6 Feature/autoloader
  composer.json
  index.php
Labels: enhancement

#10 added php platform constraints
  .gitattributes
  composer.json
Labels: documentation, enhancement

#11 Update composer.json
  composer.json
Labels: documentation

#12 Add phpunit
  composer.json
  composer.lock
  phpunit.xml
  tests/bootstrap.php
Labels: enhancement
